name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - master # master 브랜치에 push될 때 동작

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Angular 버전에 맞는 Node.js 버전

      - name: Install dependencies
        run: npm ci

      - name: Build the Angular app
        run: ng build --output-path docs --base-href /NetflixClone/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist/
          target_branch: gh-pages
